### ISSUE TITLE
Reveal username on hover

### ISSUE THREAD

**Issue by nascentt** [luketimothyjones/YouTube-Spam-Remover#5]
I see that if i hover an avatar of a 'blocked' comment I can see the avatar ok, but if i hover the username of the commenter it does not reveal that. 
Is that an easy change that can be implemented?

**Comment by samipfjo** [comment]
Hm, that's an existing feature, they must have changed something that broke it. Thanks for the report, I'll get a fix pushed.

**Comment by samipfjo** [comment]
Turns out that was a logic issue on my end; whoops! This will be patched in tomorrow's release.
