### ISSUE TITLE
all comments marked as spam?

### ISSUE THREAD

**Issue by nascentt** [luketimothyjones/YouTube-Spam-Remover#6]
Some videos just have all comments marked as spam which makes things hard to read.

![42342342](https://github.com/samipfjo/YouTube-Spam-Remover/assets/1145722/87c45e6b-85c0-4011-b7d7-197fd0aed386)

[example video](https://www.youtube.com/watch?v=tE0SAcDQ390)

**Comment by samipfjo** [comment]
Thanks for letting me know, and for providing an example video and screenshot! That saves me a lot of headache :)

Are you using Firefox or Chrome? I'm working on an unrelated update at the moment and with my current changes I haven't seen this bug, at least on Firefox.

**Comment by nascentt** [comment]
Chrome

**Comment by samipfjo** [comment]
I was able to replicate the bug in Chrome; weirdly there was an HTML change in only the version of the site Chrome loads. Gotta love preferential treatment.

Anyway, I've patched the issue along with several others. There are a few more things I need to do before pushing the update out, but it should hit the extension stores by tomorrow evening.

Apologies for taking so long getting this patched, I've had a bunch of work stuff going on and I haven't had time until now.

**Comment by samipfjo** [comment]
This is a largely a note for myself: blurring the avatar and user handle when the avatar is flagged but the content of the comment is OK is intended behavior (as previously requested by several users). Only flagged content should trigger a full collapse. Need to verify said logic hasn't changed before pushing the next version.

All comments being flagged as per this issue is obviously not intended behavior, haha.

**Comment by samipfjo** [comment]
I've unfortunately discovered several other chrome-specific breaking issues in the process. Currently ironing those out; I'll post here again once I've submitted the new version.

**Comment by samipfjo** [comment]
Just pushed the update.

It's already out on the Mozilla store and will be out on the Chrome store whenever they get around to it (usually within a few days).

The changes they made broke a TON of features, including on Firefox. I've gotten everything that I could find fixed, so the extension should be back to 100% until they hit the "needlessly rename things" spot on their wheel of pain again.

I wanted to get the release pushed out ASAP so I haven't taken the time to clean up the git commits, so the repo isn't up to date yet. I'll hopefully get that done within the next few days.

**Comment by samipfjo** [comment]
Update is live on the Chrome store
